env:
 - RACKET_VERSION=5.3.5

before_install:
 - curl -L https://github.com/greghendershott/travis-racket/releases/v0.1/1886/install-racket.sh | sh

script:
 - /usr/racket/bin/racket -t core-test.rkt
